### PR TITLE
Fixed #178

### LINKED ISSUE #178: Parking Space timers not cancelling at the end of the round.
**Describe the bug**
Screen Shot 2020-02-26 at 17 56 17

- Player 1 entered player 0's space when there was less than three seconds remaining in round 0.
- Player 1 was disconnected (as expected).
- Player 1 then claimed the space after the PreRoundEvent for round 1. Therefore had claimed the space in round 1.
- Player 0 then did not claim a space in the next round.
- Player 0 did not get disconnected at the end of the round. Assuming it is to do with the fact that Player 1 had claimed a space but was no longer in the game. 

**Expected behavior**
- Player 1 should not have claimed the space. 
- Player 0 should have been eliminated in round 1.

### PR DESCRIPTION
**Pull request by ChrisGora**
- On Round End the timers are cancelled
- Also added an if statement in OnSpaceClaimed to check if a space is still enabled (just in case)

### CODE REVIEW

File: ProjectFiles/Assets/Scripts/Game/Core/Parking/ServerParkingSpaceManager.cs [hunk 1]
```diff
@@ -14,6 +15,13 @@ public class ServerParkingSpaceManager : ParkingSpaceManager {
         public event SpaceClaimedDelegate SpaceClaimedEvent;
 
 
+        public override void OnRoundEnd(ushort roundNumber) {
```
Comment (RileyEv) [inline ProjectFiles/Assets/Scripts/Game/Core/Parking/ServerParkingSpaceManager.cs:29]: might be being picky and is probably an edge case, but should we set a flag `OnRoundEnd` that says if a timer triggers while we are resetting the timers it shouldn't count?

Currently we could have:
1. End the round.
2. End timers 1,2,3,4,5,6
3. Timer 8 gets triggered
4. End timers 7,8,9

Would we want timer 8 to count?

Comment (ChrisGora) [reply ProjectFiles/Assets/Scripts/Game/Core/Parking/ServerParkingSpaceManager.cs:29]: I vote no, because the flag will make no difference to the player.

Comment (RileyEv) [reply ProjectFiles/Assets/Scripts/Game/Core/Parking/ServerParkingSpaceManager.cs:29]: But wont it be the difference between the server saying they've claimed a space and not a space.

Could we then end up sending packets saying someones claimed a space in a round after the round has ended?

Comment (RileyEv) [reply ProjectFiles/Assets/Scripts/Game/Core/Parking/ServerParkingSpaceManager.cs:29]: I've changed this so that it doesn't happen anymore.

```cs
cancellingTimers = true;
foreach (var space in parkingSpacesBySpaceID.Values) {
    space.Timer.Reset();
}
cancellingTimers = false;
```

If a timer triggers and `cancellingTimers` is true then it is ignored.
