### PR TITLE
Collider Fixes

### LINKED ISSUE #88: Box Collider causing issues with rigidbody simulation
For some reason adding a box collider to the car causes the driving to get messed up. Which is odd as the car has sphere colliders for the wheels.

We might need to use different physics layers to help solve the problem. More investigation is needed.

(I don't think this will be solved in time for the prototype. It doesn't really affect the driving, it's more of an issue when we start driving cars into each other and scenery).

### PR DESCRIPTION
**Pull request by Keywarn**
Fixed issue with colliders causing the car to roll over. 
Resolves #88

### CODE REVIEW

**Review by ghost — APPROVED** [review]

File: ProjectFiles/Assets/Scripts/Vehicle/VehicleDriver.cs [hunk 1]
```diff
@@ -19,6 +19,7 @@ public class VehicleDriver : MonoBehaviour
         void Start()
         {
             body = gameObject.GetComponent<Rigidbody>();
+            body.centerOfMass = transform.Find("centreOfMass").transform.localPosition;
```
Comment (RileyEv) [inline ProjectFiles/Assets/Scripts/Vehicle/VehicleDriver.cs:22]: WTF is this how dare you do this

**Review by RileyEv — CHANGES_REQUESTED** [review]
